[project]
name = "rust-boost"
authors = ["Rust Boost Team <team@rustboost.dev>"]
description = "A decentralized collaboration platform for Rust developers"
telemetry = false
requirements = []
[contracts.rust-boost-payments]
path = "contracts/rust-boost-payments.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
